require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  Exclude:
    - Gemfile
    - Rakefile
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'script/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'
    - 'bin/*'
    - 'config/initializers/*'
  
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true
  
Style/HashTransformValues:
  Enabled: true
